apiVersion: v1
kind: Service
metadata:
  name: itau-pj-recuperacao-service
spec:
  selector:
    app: itau-pj-recuperacao
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
