apiVersion: v1
kind: Service
metadata:
  name: recuperacao-service
spec:
  selector:
    app: recuperacao
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Expor como LoadBalancer para acesso externo
